project:
  type: website
  preview:
    port: 6499
  resources: 
    - assets/*.png
    - assets/*.jpg

website:
  title: "Tiles Collector"
  description: "My Entry for Ludum Dare 58. A game made in 48 hours."
  site-url: "https://dhmmasson.github.io/ld58"
  favicon: assets/favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: CHANGELOG.md
        text: Changelog
  open-graph:   
    locale: "en_US"    
  twitter-card: 
    card-style: "summary_large_image"
    creator: "@dhmmasson"
    image: "assets/splash.jpg"
    image-width: 800
    image-height: 418
  page-footer: 
    left: 
      - text: "Ludum Dare 58 (2025) - Dimitri Masson - MIT License"
    right:
      - text: "Star the project on GitHub"
      - href: https://github.com/dhmmasson/ld58
      - icon: github


format:
  html:
    theme: cosmo
    css: stylesheets/styles.css    
    toc: false
    page-layout: full
    email-obfuscation: javascript
    appendix-cite-as: display
    title-block-style: manuscript
    license: "MIT"
    gutter-width: 0rem
    grid:
      sidebar-width: 0px




